version: "3.9"
services:
  node_n:
    build: 
    image: ui_erp:latest-${BUILD_NUMBER}
    container_name: node_n
    environment:
        - TZ=Asia/Kolkata
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - "/etc/timezone:/etc/timezone:ro" 
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3000:3000
    networks:
      - default

    restart: always